### ISSUE TITLE
SysID add-on MV and CV selection does not appear to work with Seeq R57. Works fine with R56

### ISSUE THREAD

**Issue by anvenkat18** [BYU-PRISM/Seeq#30]
The add-on works fine with R56 but fails to load/show MV and CV signals in R57 (shows no data available). I know we had seen that earlier and attempted to address it. @imanbabaei let's taker a look once you are in. While we are at it, lets check R58 also.

**Comment by anvenkat18** [comment]
R56:
<img width="1244" alt="R56" src="https://user-images.githubusercontent.com/49081896/203136988-fa0e4536-c162-4a90-abbb-4b76c4ba2c14.png">
R57:
<img width="1361" alt="R57" src="https://user-images.githubusercontent.com/49081896/203137008-1b52a966-2758-408d-81da-a1fd9d432d0c.png">

**Comment by imanbabaei** [comment]
It looks like starting from `seeq==56.1.8.184.12`, we have some changes in spy.pull and spy.search:
spy < 56.1.8.184.12:
spy.pull(... , quiet=True)

spy >= 56.1.8.184.12:
spy.pull(... , status=spy.Status(quiet=True))

Let's release v0.4.1 apply this change and the fix for issue #22, and check again.
